### ISSUE TITLE
add CLOSED-CAPTIONS=NONE  to transcoded m3u8 manifests

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/transcoder#21]
from @DispatchCommit : 

https://developer.apple.com/library/archive/qa/qa1801/_index.html
iOS 7 now supports the TYPE attribute of the EXT-X-MEDIA tag having a value of CLOSED-CAPTIONS. This allows for explicit declaration of closed caption content in the playlist file. See the HTTP Live Streaming Draft Protocol Specification for the details.
iOS 7 also supports a CLOSED-CAPTIONS attribute for the EXT-X-STREAM-INF tag. You can declare the absence of closed caption content in the playlist by specifying CLOSED-CAPTIONS=NONE on the EXT-X-STREAM-INF tag. The "Unknown CC" option as shown in Figure 1 will not be displayed in the selection when the absence of closed caption content is declared.
Also, if the media does not contain alternate audio or subtitles, and the absence of closed caption content is declared, the alternate track button will not be displayed.
Transcoded videos show "Unknown CC"

Please add CLOSED-CAPTIONS=NONE  to transcoded m3u8 manifests to fix.

This will address https://github.com/lbryio/lbry-desktop/issues/6233 for the app team, as the player is only behaving as Apple specifies it should given the metadata on the file.

**Comment by andybeletsky** [comment]
Retroactive fix deployed.
